# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e285055402a0c71a75832ac4441c161463b5676f483d05f5cec6f3ac5904d537b0c2bd9a0e093d7e82107cd6728a8d048fdfc60116cb054e2ef926c887531cd9

test:
  secret_key_base: 92877eb9e1f8df566d2fa962168c6cc4274d34b20a01e68738716e781231c47f46d5719ec1d4683f453bbeaa91322fd8355848ddcd118fd3978c8f8f7fced28b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
